[[constraint]]
  name = "github.com/emersion/go-imap"
  branch = "v1"

[[constraint]]
  branch = "master"
  name = "github.com/emersion/go-imap-idle"

[prune]
  go-tests = true
  unused-packages = true
